package com.claudetabs

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Naming a tab after the conversation's opening question.
 *
 * This is the source that actually fires. Claude Code 2.1.226 gates its auto-naming on
 * `sessionKind === "bg"`, so an interactive terminal session keeps a directory-derived name
 * (`riderclaudetabs-4f`) for its whole life and [ClaudeTabsHelpers.meaningfulSessionName]
 * returns null every time — verified against two live sessions and against the CLI binary.
 *
 * The transcript's first real user turn is the same text Claude's own `--resume` picker
 * shows, so it reads like a summary without anything having to summarise it.
 *
 * The hard part is that a transcript does not open with what the person typed. Every case
 * below is a line shape taken from a real transcript under `~/.claude/projects`.
 */
class FirstPromptNameTest {

    private fun userLine(content: String, extra: String = "") =
        """{"parentUuid":null,"isSidechain":false,"type":"user","message":{"role":"user","content":${quote(content)}}$extra}"""

    private fun quote(s: String) = buildString {
        append('"')
        for (c in s) when (c) {
            '"' -> append("\\\"")
            '\\' -> append("\\\\")
            '\n' -> append("\\n")
            else -> append(c)
        }
        append('"')
    }

    @Test fun usesTheFirstThingThePersonTyped() {
        val lines = sequenceOf(
            """{"type":"mode","mode":"normal","sessionId":"abc"}""",
            userLine("빌드 다시 해줘"),
        )
        assertEquals("빌드 다시 해줘", ClaudeTabsHelpers.firstPromptName(lines))
    }

    @Test fun skipsAssistantAndToolTurns() {
        val lines = sequenceOf(
            """{"type":"assistant","message":{"role":"assistant","content":"I'll start by reading the file."}}""",
            userLine("fix the flaky test"),
        )
        assertEquals("fix the flaky test", ClaudeTabsHelpers.firstPromptName(lines))
    }

    /**
     * A tool result is a user-role turn whose content is an array of blocks, not a string.
     * Taking it would name the tab after a file listing.
     */
    @Test fun ignoresToolResultsDisguisedAsUserTurns() {
        val lines = sequenceOf(
            """{"type":"user","message":{"role":"user","content":[{"type":"tool_result","content":"total 48"}]}}""",
            userLine("summarise it"),
        )
        assertEquals("summarise it", ClaudeTabsHelpers.firstPromptName(lines))
    }

    /**
     * The first turn of every session carries injected context. Claude's own reader slices
     * past the last `</system-reminder>`; anything less names every tab after the same
     * boilerplate.
     */
    @Test fun slicesPastInjectedContext() {
        val content = "<system-reminder>\nThe session's working directory has changed.\n</system-reminder>\n로그 확인해줘"
        assertEquals("로그 확인해줘", ClaudeTabsHelpers.firstPromptName(listOf(userLine(content)).asSequence()))
    }

    @Test fun skipsSlashCommandEchoes() {
        val lines = sequenceOf(
            userLine("<command-name>/cd</command-name>\n<command-args>RiderClaudeTabs</command-args>"),
            userLine("<local-command-stdout>Moved to /Users/x</local-command-stdout>"),
            userLine("현재 버전에서 호환되게 수정해줘"),
        )
        assertEquals("현재 버전에서 호환되게 수정해줘", ClaudeTabsHelpers.firstPromptName(lines))
    }

    @Test fun skipsTheLocalCommandCaveatBanner() {
        val lines = sequenceOf(
            userLine("Caveat: The messages below were generated by the user while running local commands."),
            userLine("run the tests"),
        )
        assertEquals("run the tests", ClaudeTabsHelpers.firstPromptName(lines))
    }

    @Test fun skipsMetaTurns() {
        val lines = sequenceOf(
            userLine("bootstrap context", extra = ""","isMeta":true"""),
            userLine("actual question"),
        )
        assertEquals("actual question", ClaudeTabsHelpers.firstPromptName(lines))
    }

    @Test fun collapsesNewlinesSoTheTabStripStaysOneLine() {
        val name = ClaudeTabsHelpers.firstPromptName(listOf(userLine("fix this:\n\n  - a\n  - b")).asSequence())
        assertEquals("fix this: - a - b", name)
    }

    @Test fun truncatesAtAWordBoundary() {
        val long = "please refactor the entire authentication module from scratch"
        val name = ClaudeTabsHelpers.firstPromptName(listOf(userLine(long)).asSequence())!!
        assertTrue("'$name' should end with an ellipsis", name.endsWith("…"))
        assertTrue("'$name' should be within budget", name.length <= ClaudeTabsHelpers.PROMPT_NAME_MAX_CHARS + 1)
        assertTrue("'$name' should cut at a space", long.startsWith(name.dropLast(1)))
    }

    /**
     * Korean and Japanese run without spaces. Insisting on a word boundary would cut the
     * whole thing away and leave an ellipsis.
     */
    @Test fun truncatesUnspacedTextWithoutLosingIt() {
        val long = "인텔리제이플러그인의터미널탭상태표시기능을전부다시구현해주세요그리고테스트도"
        val name = ClaudeTabsHelpers.firstPromptName(listOf(userLine(long)).asSequence())!!
        assertEquals(ClaudeTabsHelpers.PROMPT_NAME_MAX_CHARS + 1, name.length)
        assertTrue(name.endsWith("…"))
        assertTrue(long.startsWith(name.dropLast(1)))
    }

    /**
     * A tab name is not a private place — it goes on the tab strip, into names.json, and
     * into the restore file. One of the real transcripts this was checked against opens
     * with a GitHub token, which would have ended up in all three.
     */
    @Test fun neverNamesATabAfterAPastedCredential() {
        val lines = sequenceOf(
            userLine("ghp_EXAMPLEONLYnotarealtoken0123456789"),
            userLine("이 토큰으로 레포 만들어줘"),
        )
        assertEquals("이 토큰으로 레포 만들어줘", ClaudeTabsHelpers.firstPromptName(lines))
    }

    @Test fun recognisesTheCommonTokenShapes() {
        for (secret in listOf(
            "ghp_abcdefghijklmnop",
            "github_pat_11ABCDE",
            "glpat-xxxxxxxxxxxx",
            "sk-ant-api03-abcdef",
            "xoxb-123-456-abcdef",
            "AKIAIOSFODNN7EXAMPLE",
            "-----BEGIN OPENSSH PRIVATE KEY-----",
            "dBv3nQ8xKm2Lp9Rt4Wy7Zc1Fh6Jd0Sg5Ub8Ne3Ai",
        )) {
            assertTrue("should be caught: $secret", ClaudeTabsHelpers.looksLikeSecret(secret))
        }
    }

    /** The guard must not swallow ordinary questions, including long URLs and paths. */
    @Test fun doesNotMistakeOrdinaryTextForASecret() {
        for (ok in listOf(
            "fix the login flow",
            "https://github.com/acme-org/example-service/pull/1234/files",
            "/Users/x/projects/example-service/src/main/kotlin/Application.kt",
            "이 스크립트가 왜 실패하는지 확인해줘",
            "skip the cache",
        )) {
            assertFalse("should be allowed: $ok", ClaudeTabsHelpers.looksLikeSecret(ok))
        }
    }

    @Test fun returnsNullWhenNothingUsableIsThere() {
        val lines = sequenceOf(
            """{"type":"mode","mode":"normal"}""",
            """{"type":"assistant","message":{"role":"assistant","content":"hi"}}""",
        )
        assertNull(ClaudeTabsHelpers.firstPromptName(lines))
    }

    @Test fun survivesMalformedLines() {
        val lines = sequenceOf("""{"type":"user",""", "not json at all", userLine("still works"))
        assertEquals("still works", ClaudeTabsHelpers.firstPromptName(lines))
    }

    /** A reminder block with nothing after it is context, not a question. */
    @Test fun ignoresATurnThatIsOnlyInjectedContext() {
        val content = "<system-reminder>\nbackground info\n</system-reminder>"
        val lines = sequenceOf(userLine(content), userLine("the real one"))
        assertEquals("the real one", ClaudeTabsHelpers.firstPromptName(lines))
    }
}
